### ISSUE TITLE
Equivalent inverse parser or manyTill parser?

### ISSUE THREAD

**Issue by ajay-addepalle** [typemeta/funcj#1]
How would i implement a parser that consumes and returns all characters until another Parser succeeds?
I'm figuring out how to parse comment string between a comment char and end of line.
I've looked at the the Haskell Parsec documentation too and I found this that might meet my need. https://hackage.haskell.org/package/parsec-3.1.11/docs/src/Text.Parsec.Combinator.html#manyTill

**Comment by jon-hanson** [comment]
I think you can use `p.many().andL(end)`. I tried it on a few tests and it seems to work, but let me know if it doesn't.

**Comment by ajay-addepalle** [comment]
Yes works, p in this case is a parser that is satisfy combinator checking for a failure of end . Cheers!
