### ISSUE TITLE
IList::flatmap does not assign result properly

### ISSUE THREAD

**Issue by AHeise** [typemeta/funcj#12]
A call to flatmap always results in a cast error, since the return value of addAll is not used.

https://github.com/typemeta/funcj/blob/24707271f5a637f50575817eb8a80e2051144fa3/core/src/main/java/org/typemeta/funcj/data/IList.java#L656

Additionally, shouldn't flatmap return an IList? flatmap may result in an empty list.

**Comment by jon-hanson** [comment]
Thanks. Will fix shortly.
