### ISSUE TITLE
Need help with my grammar definition

### ISSUE THREAD

**Issue by kpadmasola** [typemeta/funcj#25]
Hi Jon,

I am trying to define a grammar for parsing a string that has something like a path structure, I have made some progress, but now I am stuck and would really appreciate any pointers on what I am doing wrong and how I can fix it.

I am trying to parse a kind of path which has segments. The rules are as follows:

- A segment can be a normal, quoted, wildcard or wildcard_suffix segment
- A path consists of one or more segments separated by a period `.`
- normal segment consists of 0-9 a-z A-Z and _  characters
- quoted segment is the same syntax as a JSON string
- wildcard segment consists of a single `*` character
- wildcard_suffix segment consists of a quoted segment (aka JSON string) followed by a `*` character
- wildcard segment and wildcard_suffix segment can only appear as the last segment of a path.

Examples:
single segment paths: `a`, `"*"`, `"a"`,  `*`
multi segment paths: `a.b`, `a."b"*`, `a.*`

I am able to parse single segment paths all right, but I am getting stuck trying to parse multi segment paths.

```java
// singleSegmentPath works fine for parsing paths with only one segment
   private static final Parser<Chr, Path> singleSegmentPath =
      choice(
         quotedSegment,
         wildcardSuffixSegment,
         wildcardSegment,
         normalSegment
      ).map(Model2::path);

// parser is for parsing both single and multi segment paths, but does not work
   private static final Parser<Chr, Path> parser =
      choice(normalSegment, quotedSegment)
         .andL(period).many()
         .and(choice(
            quotedSegment,
            wildcardSuffixSegment,
            wildcardSegment,
            normalSegment
         ))
         .map(segments -> segment -> Model2.path(segments, segment));
```

Please let me know if you need more information.

thank you!

**Comment by jon-hanson** [comment]
It's difficult to diagnose without seeing the definition of `quotedSegment` et al. If you can post a minimal complete example (i.e. one that compiles) that exhibits the problem, then I can take a look.

Also, can you elaborate on what you mean when you say it doesn't work. Do you get an error?

**Comment by kpadmasola** [comment]
Hi Jon,

Thank you for your response. I have created a sample at https://github.com/kpadmasola/funcj-sample/tree/master

Yes, I get an error when I run the program. I'm not sure if I am making any mistake when defining the grammar.

The App.java has example paths that need to be parsed. It contains both single segment and multi segment paths.
When I use the `singleSegmentPath` parser (https://github.com/kpadmasola/funcj-sample/blob/master/src/main/java/org/example/Grammar.java#L102), the single segment paths get parsed correctly and multi segment paths fail as expected.

I defined multi segment path parser here https://github.com/kpadmasola/funcj-sample/blob/master/src/main/java/org/example/Grammar.java#L110, which is supposed to handle both single and multi segment paths, but it is now failing right on the first single segment path test in App.java.

I'd like the grammar to be able to handle both single and multi segment paths. The only complexity is in the last segment -- it can be just a `*`(wildcard segment)  or `"abc"*` (wildcard suffix segment) or `xyz` (normal segment) or `"pqr"` (quoted segment). I can manually handle the complexity of last segment in my application and simplify the grammar to include only normal segment and quoted segment. But before I take that route, I just want to understand why I am not able to handle it it the grammar.

Please let me know if you need any more details. Appreciate your help with this.

thanks,
Krishna
PS: for quoted segment, I used your code from json parser grammar for json string parsing.

**Comment by jon-hanson** [comment]
I think the first issue is this:

```
      choice(normalSegment, quotedSegment)
         .andL(period).many()
```

This rule is saying that it will accept zero or more of a segment followed by a period. So these all parse:

Segment Period
Segment Period Segment Period

etc. However a Segment on its own does not parse because it's not followed by a period. So the first test in app ("a") fails for this reason.

**Comment by kpadmasola** [comment]
thanks, that makes sense.
