### ISSUE TITLE
Calling many() on an uninitialized reference throws exception but it shouldn't.

### ISSUE THREAD

**Issue by melrief** [typemeta/funcj#27]
There is a check in [`many()`](https://github.com/typemeta/funcj/blob/9f3b377eef83ba399a6148c5611d12447114dd5b/parser/src/main/java/org/typemeta/funcj/parser/Parser.java#L339) that throws exception if `this` doesn't accept empty symbol via the `acceptsEmpty` method. [`acceptsEmpty` is not implemented](https://github.com/typemeta/funcj/blob/9f3b377eef83ba399a6148c5611d12447114dd5b/parser/src/main/java/org/typemeta/funcj/parser/Ref.java#L24) on uninitialized Refs which prevents the combinator `many` from being used on res:

```java
Ref<Chr, Chr> r = Parser.ref();
Parser<Chr, IList<Chr>> rs = r.many();
```

 I think the check should be postponed to when the ref is set.

**Comment by jon-hanson** [comment]
Thanks for reporting the issue. With regards to your proposed solution, AFAICS postponing the check is difficult as the `Ref` parser has no knowledge of the parsers that refer to it, so there is no straightforward way for the ref to invoke the check when it's initialised.

I guess a proper solution would entail the ref maintaining a list of deferred checks that would be executed when it's initialised.

The simplest thing I can do here for now is to simply disable the check in `many` if the current parser is a `Ref`. Let me know if you see a better way to fix this.

**Comment by jon-hanson** [comment]
I've checked in a fix.

**Comment by melrief** [comment]
The fix works, thank you for the quick response!
