### ISSUE TITLE
Request: Change visibility of various parser fields in `JsonCombParser` to public

### ISSUE THREAD

**Issue by kpadmasola** [typemeta/funcj#28]
The `JsonCombParser` class has various predefined parsers for parsing various JSON types/primitives such as string, boolean, number, digit, hexDigit etc. These definitions are very useful. However, currently they cannot be used externally as their visibility scope is package.

My request is to make them visible with `public` scope so that consumers of this library can avoid code duplication.

Please let me know if you have any questions/suggestions. Thanks!

**Comment by kpadmasola** [comment]
Great! Could you please bump the version and release the updated library with these changes? Thanks!

**Comment by kpadmasola** [comment]
Hi @jon-hanson Is it possible to release an updated version with these changes? Please let me know if there is something I can do to help with this. Thank you.

**Comment by jon-hanson** [comment]
Hmmm, Maven didn't upload any artefacts to Sonatype, weird.

**Comment by kpadmasola** [comment]
> Hmmm, Maven didn't upload any artefacts to Sonatype, weird.

Thanks for preparing the release though. What could be the issue causing it? invalid credentials perhaps? Are there build logs that could help identify the root cause?

**Comment by jon-hanson** [comment]
0.6.18 should now be available.
