### ISSUE TITLE
Help: Parsing expressions with operator precedence.

### ISSUE THREAD

**Issue by kpadmasola** [typemeta/funcj#33]
@jon-hanson:
Given an arithmetic expression such as `2 + 3 * 5`, how should we define the grammar so that it is parsed as `2 + (3 * 5)` and not as `(2 + 3) * 5` ?

thanks in advance!

**Comment by jon-hanson** [comment]
The conventional simple route is to split the mult/div operators and the add/sub operators into two separate rules, and to give the mult/div rule precedence in the grammar, e.g.:

    expr = prod chainl1 addSub
    prod = term chainl1 multDiv
    multDiv = mult | div
    addSub = add | sub

By structuring the rules this way, an expression such as:

    1+2*3

will be parsed as

        expr
          |
        prod
          |
        mult
       /       \
   term    add
     |       /       \
    1   term    term
           |          |
          2         3

There is an example test grammar in the library that uses that approach here:

https://github.com/typemeta/funcj/blob/master/parser/src/test/java/org/typemeta/funcj/parser/expr/Grammar.java#L65

**Comment by kpadmasola** [comment]
thanks!
