### ISSUE TITLE
Parser doesn't try the alternative choice if first parser fails

### ISSUE THREAD

**Issue by etsinko** [typemeta/funcj#34]
Hi,
I'm not sure if I follow the parsing correctly but I expected the following parser to be able to parse this:
```java

        var r = Parser.choice(
                              Text.string("AB"),
                              Text.string("AC"))
                      .parse(Input.of("AC"));
       System.out.println(r.isSuccess()); // false, although expect to be true
```
Shouldn't it try the second option ('AC') when the first one fails?

**Comment by jon-hanson** [comment]
It's a parser for LL(1) grammars, meaning at every stage the parser can determine the next rule to apply by looking no more than 1 token ahead. For your grammar it needs to look 2 characters ahead to decide which of those two rules should apply.

If you rewrite your grammar as something like:

    var r = Text.string("A")
            .and(Parser.choice(Text.string("B"), Text.string("C")))
            .map(String::concat)
            .parse(Input.of("AC"));
    System.out.println(r.isSuccess());

then it should work.

**Comment by etsinko** [comment]
Got it! Thanks for the explanation
