### ISSUE TITLE
Code coverage not complete for property tests in StateTe.java

### ISSUE THREAD

**Issue by Harmoniguy** [typemeta/funcj#36]
All property tests in the `StateTest.java` have missing coverage over lines 172 and 173 of `Trampoline.java`. 
I could not figure out a good way to get this coverage while keeping in the scope of the test, as I tried to add something similar to the non-property test testSequenceList. testSequenceList does cover this code, but ideally I would expect that each property test would have as much coverage as possible. This may be out of the scope of the tests.

**Comment by jon-hanson** [comment]
StateTest isn't supposed to test Trampoline other than indirectly by virtue of the fact that State uses it. Lines 172-173 of Trampoline are covered by the TrampolineTest.testFibonacci() test.
