### ISSUE TITLE
Issue with string parser when tokens begin by the same letter

### ISSUE THREAD

**Issue by vintaerj** [typemeta/funcj#38]
Hello,

When i use the below parser, i have always an error on the second string parser "raw".

```java
final Parser<Chr, String> parser = choice(string("right"), string("raw"));
System.out.println(locationParser.parse(Input.of("raw")).getOrThrow());
```

I have this error: 
`Exception in thread "main" java.lang.RuntimeException: Failure at position 1, expected=r`

Same with `or` method.

What i understand is that we can make string parser that begin by the same letter ?

Thanks you

**Comment by jon-hanson** [comment]
It's an LL(1) parser meaning the grammar has to be such that the parser can determine the next rule to apply at each stage by looking one character ahead. Your grammar doesn't satisfy this requirement because you have two rules that have the same first character.

You can work around this by moving the leading 'r' outside of the choice, e.g.:

```java
final Parser<Chr, String> parser =
        string("r")
                .and(choice(string("ight"), string("aw")))
                .map(String::concat);
System.out.println(parser.parse(Input.of("raw")).getOrThrow());
```

**Comment by vintaerj** [comment]
Thanks you for you response. Actually, i use an enum to define my tokens like this:

final Parser<Chr, Location> locationParser = Arrays.stream(LocationType.values())
                .map(locationType -> string(locationType.getName()).map(LocationType::getByName))
                .reduce(Parser::or)
                .orElseThrow();

I don't think that you workaround could work with this approach :/

**Comment by jon-hanson** [comment]
If you convert the input stream to a stream of tokens, and then parse that, you shouldn't have an issue.

An [example](https://github.com/typemeta/funcj/tree/master/parser/src/test/java/org/typemeta/funcj/parser/enumexpr).
